### ISSUE TITLE
Running on Windows produce event loop errors

### ISSUE THREAD

**Issue by cybermaggedon** [cybermaggedon/gnucash-uk-vat#14]
Once the --init-config problem is worked around, get event loop problems on Windows.  Looks like all operations work (fetching obligations, fetching VAT returns, computing data), but the event loop throws an exception on exit. This is using Python 3.10 as installed from VS on Win 10.
```
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000029F6404F0A0>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\[proactor_events.py](http://proactor_events.py/)", line 116, in __del__
    self.close()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\[proactor_events.py](http://proactor_events.py/)", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\[base_events.py](http://base_events.py/)", line 750, in call_soon
    self._check_closed()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\[base_events.py](http://base_events.py/)", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by awltux** [comment]
I believe I fixed this in [my pull request](https://github.com/cybermaggedon/gnucash-uk-vat/pull/22/commits/fbebb9d9dc4435615dc6e08cfc26309e0e9c5062)
