### ISSUE TITLE
Error trying to run gui

### ISSUE THREAD

**Issue by MichaelBScott** [cybermaggedon/gnucash-uk-vat#6]
I'm getting the following error when running with the --assist resulting in the next button being disabled after selecting a gnucash file.
Does anyone know how to resolve this?

$ gnucash-uk-vat --assist
Traceback (most recent call last):
  File "~/.local/lib/python3.10/site-packages/gnucash_uk_vat/assist.py", line 708, in prepare
    self.check_file()
  File "~/.local/lib/python3.10/site-packages/gnucash_uk_vat/assist.py", line 614, in check_file
    raise e
  File "~/.local/lib/python3.10/site-packages/gnucash_uk_vat/assist.py", line 609, in check_file
    accts =  accounts.Accounts(self.vat.config)
AttributeError: module 'gnucash_uk_vat.accounts' has no attribute 'Accounts'

**Comment by cybermaggedon** [comment]
I'll take a look tomorrow, maybe I missed a checkin. Where did you install from, github clone, or pypi?

**Comment by MichaelBScott** [comment]
Ok, thank you.
I installed is as described by running:
pip3 install git+https://github.com/cybermaggedon/gnucash-uk-vat

I also tried updating the kind property in config.json to try both gnucash and piecash but the error was the same.

**Comment by cybermaggedon** [comment]
Thanks, ah... I think I missed a checkin on assist.py.

**Comment by cybermaggedon** [comment]
Error reproduced, should have an answer for you soon

**Comment by MichaelBScott** [comment]
Thank you

**Comment by cybermaggedon** [comment]
A couple of code refactors broke assist, the head of master contains the fix: b6b776fb176abda30cb885bcda6ad81a32e53227

**Comment by MichaelBScott** [comment]
Thank you I no longer get the error.
